name: "Hello Actions"
description: "Greet yourself"
author: "octocat@github.com"

inputs:
  REVOLUTION_IS_MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

  runs:
    using: "docker"
    image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"
