name: A workflow to test the AMI update
on: workflow_dispatch

jobs:
  hello_world_job:
    name: update AMI ID test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update AMI ID in tfvars file
        run: sed -i 's/^jva_ami_id =.*$/jva_ami_id = \"AMI-ID-NEW\"/' ./AWS_JVADMIN/jvadmin-staging.tfvars
      - name: Commit updated tfvars file
        run: |
          git config --global user.name 'JVCICD'
          git config --global user.name 'helpdesk@joinvision.com'
          git commit -am "Updated AMI ID in staging tfvars file"
          git push